/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "hex.h"
/* Header for class HEX_src_jeu_InterfaceAvecC */

#ifndef _Included_HEX_src_jeu_InterfaceAvecC
#define _Included_HEX_src_jeu_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    choix_mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HEX_src_jeu_InterfaceAvecC_choix_1mode
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    saveDisponible
 * Signature: ()Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_HEX_src_jeu_InterfaceAvecC_saveDisponible
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    creer_information_joueur_1
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_HEX_src_jeu_InterfaceAvecC_creer_1information_1joueur_11
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    choixTaille
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HEX_src_jeu_InterfaceAvecC_choixTaille
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    initialisationTab
 * Signature: (I)[C
 */
JNIEXPORT jcharArray JNICALL Java_HEX_src_jeu_InterfaceAvecC_initialisationTab
  (JNIEnv *, jobject, jint);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    loadSaveSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HEX_src_jeu_InterfaceAvecC_loadSaveSize
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    loadSaveTab
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_HEX_src_jeu_InterfaceAvecC_loadSaveTab
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    action_joueur
 * Signature: ([CLjava/lang/Boolean;I)I
 */
JNIEXPORT jint JNICALL Java_HEX_src_jeu_InterfaceAvecC_action_1joueur
  (JNIEnv *, jobject, jcharArray, jobject, jint);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    question_quitter
 * Signature: ()Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_HEX_src_jeu_InterfaceAvecC_question_1quitter
  (JNIEnv *, jobject);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    gagnant
 * Signature: ([CI)C
 */
JNIEXPORT jchar JNICALL Java_HEX_src_jeu_InterfaceAvecC_gagnant
  (JNIEnv *, jobject, jcharArray, jint);

/*
 * Class:     HEX_src_jeu_InterfaceAvecC
 * Method:    saveQuestion
 * Signature: ([CI)V
 */
JNIEXPORT void JNICALL Java_HEX_src_jeu_InterfaceAvecC_saveQuestion
  (JNIEnv *, jobject, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
